### ISSUE TITLE
Unable to run image as docker container - application.yaml malformed ffmpeg profile commands

### ISSUE THREAD

**Issue by rubenkr** [segator/proxylive#16]
Hi there,

first of all thank you very much for your great work. I can hardly express in words how much I appreciate the fact you share your knowledge and code here. I tried to run the instance as follow

` docker run --name=proxylive -p 3080:8080 --restart=always -d -v /mnt/application.yml:/app/application.yml:ro segator/proxylive`

I am using the application.yml from a previous [issue](https://github.com/segator/proxylive/issues/15).

Getting following docker logs errors:
```
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
11:29:20.899 [main] DEBUG org.springframework.boot.context.logging.ClasspathLoggingApplicationListener - Application failed to start with classpath: [jar:file:/app/proxyLive.jar!/BOOT-INF/classes!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/spring-boot-starter-web-2.1.3.RELEASE.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/spring-boot-starter-2.1.3.RELEASE.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/spring-boot-2.1.3.RELEASE.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/spring-boot-autoconfigure-2.1.3.RELEASE.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/spring-boot-starter-logging-2.1.3.RELEASE.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/logback-classic-1.2.3.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/logback-core-1.2.3.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/log4j-to-slf4j-2.11.2.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/log4j-api-2.11.2.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/jul-to-slf4j-1.7.25.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/javax.annotation-api-1.3.2.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/spring-core-5.1.5.RELEASE.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/spring-jcl-5.1.5.RELEASE.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/snakeyaml-1.23.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/spring-boot-starter-json-2.1.3.RELEASE.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/jackson-datatype-jdk8-2.9.8.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/jackson-datatype-jsr310-2.9.8.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/jackson-module-parameter-names-2.9.8.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/spring-boot-starter-tomcat-2.1.3.RELEASE.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/tomcat-embed-core-9.0.16.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/tomcat-embed-el-9.0.16.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/tomcat-embed-websocket-9.0.16.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/hibernate-validator-6.0.14.Final.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/validation-api-2.0.1.Final.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/jboss-logging-3.3.2.Final.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/classmate-1.4.0.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/spring-web-5.1.5.RELEASE.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/spring-beans-5.1.5.RELEASE.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/spring-webmvc-5.1.5.RELEASE.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/spring-aop-5.1.5.RELEASE.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/spring-context-5.1.5.RELEASE.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/spring-expression-5.1.5.RELEASE.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/spring-boot-starter-actuator-2.1.3.RELEASE.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/spring-boot-actuator-autoconfigure-2.1.3.RELEASE.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/spring-boot-actuator-2.1.3.RELEASE.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/micrometer-core-1.1.3.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/HdrHistogram-2.1.9.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/LatencyUtils-2.0.3.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/micrometer-registry-prometheus-1.1.3.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/simpleclient_common-0.5.0.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/simpleclient-0.5.0.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/geoip2-2.8.0.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/maxmind-db-1.2.1.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/httpclient-4.5.7.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/httpcore-4.4.11.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/commons-codec-1.11.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/jackson-databind-2.9.8.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/jackson-annotations-2.9.0.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/jackson-core-2.9.8.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/commons-compress-1.19.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/commons-io-1.3.2.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/commons-lang3-3.4.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/commons-cli-1.2.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/json-simple-1.1.1.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/junit-4.12.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/hamcrest-core-1.3.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/org.eclipse.jgit-5.7.0.202003110725-r.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/jsch-0.1.55.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/jzlib-1.1.1.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/JavaEWAH-1.1.7.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/slf4j-api-1.7.25.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/bcpg-jdk15on-1.64.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/bcprov-jdk15on-1.64.jar!/, jar:file:/app/proxyLive.jar!/BOOT-INF/lib/bcpkix-jdk15on-1.64.jar!/]
11:29:21.204 [background-preinit] DEBUG org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator - Loaded expression factory via original TCCL
11:29:21.215 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator as ValidatorFactory-scoped message interpolator.
11:29:21.216 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.resolver.TraverseAllTraversableResolver as ValidatorFactory-scoped traversable resolver.
11:29:21.216 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.util.ExecutableParameterNameProvider as ValidatorFactory-scoped parameter name provider.
11:29:21.217 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.DefaultClockProvider as ValidatorFactory-scoped clock provider.
11:29:21.217 [background-preinit] DEBUG org.hibernate.validator.internal.engine.ValidatorFactoryImpl - HV000234: Using org.hibernate.validator.internal.engine.scripting.DefaultScriptEvaluatorFactory as ValidatorFactory-scoped script evaluator factory.
11:29:22.243 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to load property source from location 'file:./application.yml'
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:554)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.loadForFileExtension(ConfigFileApplicationListener.java:500)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:467)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.lambda$null$6(ConfigFileApplicationListener.java:448)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.lambda$load$7(ConfigFileApplicationListener.java:447)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:444)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:332)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.addPropertySources(ConfigFileApplicationListener.java:207)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.postProcessEnvironment(ConfigFileApplicationListener.java:190)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:177)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:163)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:75)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:347)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
        at com.github.segator.proxylive.Application.main(Application.java:38)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'reader', line 6, column 16:
            refresh: 600 #10 minutes
                   ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:870)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:214)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:123)
        at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:547)
        at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:161)
        at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:134)
        at org.springframework.boot.env.OriginTrackedYamlLoader.load(OriginTrackedYamlLoader.java:75)
        at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:50)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.loadDocuments(ConfigFileApplicationListener.java:572)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:526)
        ... 31 common frames omitted
➜  iptv_proxylive

```

Any help is highly appreciated. Thank you in advance !

**Comment by rubenkr** [comment]
segator, thank you very much. I will retry tonight. Have a great start in the week !

**Comment by rubenkr** [comment]
I retried and get the following error. What am I doing wrongly?

`➜  proxylive git:(master) ✗ docker run --name=proxylive -p 3081:8080 --restart=always -v /mnt/WD14TB/006__DOCKER/volumes/iptv_proxylive/application.yml:/app/application.yml:ro segator/proxylive


/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
               (      (         )       )       )   (      (
               )\ )   )\ )   ( /(    ( /(    ( /(   )\ )   )\ )
              (()/(  (()/(   )\())   )\())   )\()) (()/(  (()/(   (   (    (
 ___   ___     /(_))  /(_)) ((_)\   ((_)\   ((_)\   /(_))  /(_))  )\  )\   )\      ___   ___
|___| |___|   (_))   (_))     ((_)  __((_) __ ((_) (_))   (_))   ((_)((_) ((_)    |___| |___|
              | _ \  | _ \   / _ \  \ \/ / \ \ / / | |    |_ _|  \ \ / /  | __|
              |  _/  |   /  | (_) |  >  <   \ V /  | |__   | |    \ V /   | _|
              |_|    |_|_\   \___/  /_/\_\   |_|   |____| |___|    \_/    |___|

            (         )              (                         (                     (
       (    )\ )   ( /(      (       )\ )      (       (       )\ )    *   )         )\ )
     ( )\  (()/(   )\())     )\     (()/(      )\      )\     (()/(  ` )  /(   (    (()/(
     )((_)  /(_)) ((_)\   ((((_)(    /(_))   (((_)  ((((_)(    /(_))  ( )(_))  )\    /(_))
    ((_)_  (_))     ((_)   )\ _ )\  (_))_    )\___   )\ _ )\  (_))   (_(_())  ((_)  (_))
     | _ ) | _ \   / _ \   (_)_\(_)  |   \  ((/ __|  (_)_\(_) / __|  |_   _|  | __| | _ \
     | _ \ |   /  | (_) |   / _ \    | |) |  | (__    / _ \   \__ \    | |    | _|  |   /
     |___/ |_|_\   \___/   /_/ \_\   |___/    \___|  /_/ \_\  |___/    |_|    |___| |_|_\


2020-08-24 09:53:28,471 INFO  [main] org.springframework.boot.StartupInfoLogger: Starting Application v1.0-SNAPSHOT on 4716597bedc0 with PID 7 (/app/proxyLive.jar started by root in /app)
2020-08-24 09:53:28,476 DEBUG [main] org.springframework.boot.StartupInfoLogger: Running with Spring Boot v2.1.3.RELEASE, Spring v5.1.5.RELEASE
2020-08-24 09:53:28,479 INFO  [main] org.springframework.boot.SpringApplication: No active profile set, falling back to default profiles: default
2020-08-24 09:53:32,343 INFO  [main] org.springframework.boot.web.embedded.tomcat.TomcatWebServer: Tomcat initialized with port(s): 8080 (http)
2020-08-24 09:53:32,376 INFO  [main] org.apache.juli.logging.DirectJDKLog: Initializing ProtocolHandler ["http-nio-8080"]
2020-08-24 09:53:32,405 INFO  [main] org.apache.juli.logging.DirectJDKLog: Starting service [Tomcat]
2020-08-24 09:53:32,406 INFO  [main] org.apache.juli.logging.DirectJDKLog: Starting Servlet engine: [Apache Tomcat/9.0.16]
2020-08-24 09:53:32,424 INFO  [main] org.apache.juli.logging.DirectJDKLog: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/local/lib:/usr/local/lib64:/usr/lib:/usr/lib64:/lib:/lib64:/usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib]
2020-08-24 09:53:32,549 INFO  [main] org.apache.juli.logging.DirectJDKLog: Initializing Spring embedded WebApplicationContext
2020-08-24 09:53:32,549 INFO  [main] org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext: Root WebApplicationContext: initialization completed in 3944 ms
2020-08-24 09:53:32,751 INFO  [main] com.github.segator.proxylive.config.ProxyLiveConfiguration: Your internal token is:JX1D21BW8YA7XMHKFQUZKS1165BXYO77I7BQTU46
2020-08-24 09:53:33,142 WARN  [main] org.springframework.context.support.AbstractApplicationContext: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'streamController': Unsatisfied dependency expressed through field 'channelService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'createChannelService' defined in class path resource [com/github/segator/proxylive/service/ChannelServiceFactory.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.segator.proxylive.service.ChannelService]: Factory method 'createChannelService' threw exception; nested exception is java.lang.NullPointerException
2020-08-24 09:53:33,151 INFO  [main] org.apache.juli.logging.DirectJDKLog: Stopping service [Tomcat]
2020-08-24 09:53:33,199 INFO  [main] org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener:

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-08-24 09:53:33,205 ERROR [main] org.springframework.boot.SpringApplication: Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'streamController': Unsatisfied dependency expressed through field 'channelService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'createChannelService' defined in class path resource [com/github/segator/proxylive/service/ChannelServiceFactory.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.segator.proxylive.service.ChannelService]: Factory method 'createChannelService' threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1395)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
        at com.github.segator.proxylive.Application.main(Application.java:38)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'createChannelService' defined in class path resource [com/github/segator/proxylive/service/ChannelServiceFactory.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.segator.proxylive.service.ChannelService]: Factory method 'createChannelService' threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1305)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1144)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
        ... 27 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.segator.proxylive.service.ChannelService]: Factory method 'createChannelService' threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
        ... 40 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.github.segator.proxylive.service.ChannelServiceFactory.createChannelService(ChannelServiceFactory.java:15)
        at com.github.segator.proxylive.service.ChannelServiceFactory$$EnhancerBySpringCGLIB$$b4b9b03b.CGLIB$createChannelService$0(<generated>)
        at com.github.segator.proxylive.service.ChannelServiceFactory$$EnhancerBySpringCGLIB$$b4b9b03b$$FastClassBySpringCGLIB$$23a58935.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
        at com.github.segator.proxylive.service.ChannelServiceFactory$$EnhancerBySpringCGLIB$$b4b9b03b.createChannelService(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 41 common frames omitted
`

**Comment by rubenkr** [comment]
Simply add  parameters: "-i {input} {channelParameters} to applications.yaml resolving the issues above.
