### ISSUE TITLE
Error creating bean with name 'streamController': Unsatisfied dependency expressed through field - Ubuntu 18.04

### ISSUE THREAD

**Issue by rayidi** [segator/proxylive#19]
Hi,

I'm just started to use proxylive but couldn't able run the application, while running I'm getting the following error.
Where did I go wrong?

**OS info:**

`Ubuntu 18.04.5 LTS Codename: bionic`

**JDK info:**

`openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)`

**Maven version:**

`Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.8, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-1024-gcp", arch: "amd64", family: "unix"`

**Here is my configuration file `application.yml` under `target` directory.**

```management:
    server:
        port: 8090
    endpoints:
        prometheus:
            enabled: true
        metrics:
            enabled: true
        web:
            exposure:
                include: "*"
    metrics:
        export:
            prometheus:
                enabled: true
    security:
        enabled: false

geoIP:
    enabled: false
    url: https://download.maxmind.com/app/geoip_download_by_token?edition_id=GeoLite2-City&date=20200915&suffix=tar.gz&token=some_token_goes_here
source:
    tvheadendURL: http://username:userpassword@tv.mydomain.net:9981
    epg:
        refresh: 600
    channels:
        refresh: 60
    reconnectTimeout: 15
streamTimeout: 30
```

**Here is my complete debug**

```
Z2020-09-18 13:46:45,743 INFO  [main] org.springframework.boot.StartupInfoLogger: Starting Application v1.0-SNAPSHOT on fitv with PID 29619 (/home/matcha_anu/proxylive/target/ProxyLive.jar started by root in /home/matcha_anu/proxylive/target)
2020-09-18 13:46:45,747 DEBUG [main] org.springframework.boot.StartupInfoLogger: Running with Spring Boot v2.1.3.RELEASE, Spring v5.1.5.RELEASE
2020-09-18 13:46:45,750 INFO  [main] org.springframework.boot.SpringApplication: No active profile set, falling back to default profiles: default
2020-09-18 13:46:47,724 INFO  [main] org.springframework.boot.web.embedded.tomcat.TomcatWebServer: Tomcat initialized with port(s): 8080 (http)
2020-09-18 13:46:47,749 INFO  [main] org.apache.juli.logging.DirectJDKLog: Initializing ProtocolHandler ["http-nio-8080"]
2020-09-18 13:46:47,770 INFO  [main] org.apache.juli.logging.DirectJDKLog: Starting service [Tomcat]
2020-09-18 13:46:47,770 INFO  [main] org.apache.juli.logging.DirectJDKLog: Starting Servlet engine: [Apache Tomcat/9.0.16]
2020-09-18 13:46:47,785 INFO  [main] org.apache.juli.logging.DirectJDKLog: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib]
2020-09-18 13:46:47,927 INFO  [main] org.apache.juli.logging.DirectJDKLog: Initializing Spring embedded WebApplicationContext
2020-09-18 13:46:47,927 INFO  [main] org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext: Root WebApplicationContext: initialization completed in 2112 ms
2020-09-18 13:46:48,079 INFO  [main] com.github.segator.proxylive.config.ProxyLiveConfiguration: Your internal token is:OB7YENDEO6TTF8IYSAVBJGX1T8DEC0SQM4P7JYIS
2020-09-18 13:46:48,285 WARN  [main] org.springframework.context.support.AbstractApplicationContext: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'streamController': Unsatisfied dependency expressed through field 'channelService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'createChannelService' defined in class path resource [com/github/segator/proxylive/service/ChannelServiceFactory.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.segator.proxylive.service.ChannelService]: Factory method 'createChannelService' threw exception; nested exception is java.lang.NullPointerException
2020-09-18 13:46:48,289 INFO  [main] org.apache.juli.logging.DirectJDKLog: Stopping service [Tomcat]
2020-09-18 13:46:48,312 INFO  [main] org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener:

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-09-18 13:46:48,316 ERROR [main] org.springframework.boot.SpringApplication: Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'streamController': Unsatisfied dependency expressed through field 'channelService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'createChannelService' defined in class path resource [com/github/segator/proxylive/service/ChannelServiceFactory.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.segator.proxylive.service.ChannelService]: Factory method 'createChannelService' threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1395)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
        at com.github.segator.proxylive.Application.main(Application.java:38)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'createChannelService' defined in class path resource [com/github/segator/proxylive/service/ChannelServiceFactory.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.segator.proxylive.service.ChannelService]: Factory method 'createChannelService' threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1305)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1144)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
        ... 27 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.segator.proxylive.service.ChannelService]: Factory method 'createChannelService' threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
        ... 40 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.github.segator.proxylive.service.ChannelServiceFactory.createChannelService(ChannelServiceFactory.java:15)
        at com.github.segator.proxylive.service.ChannelServiceFactory$$EnhancerBySpringCGLIB$$b2c95122.CGLIB$createChannelService$0(<generated>)
        at com.github.segator.proxylive.service.ChannelServiceFactory$$EnhancerBySpringCGLIB$$b2c95122$$FastClassBySpringCGLIB$$bb797a11.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
        at com.github.segator.proxylive.service.ChannelServiceFactory$$EnhancerBySpringCGLIB$$b2c95122.createChannelService(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 41 common frames omitted
```

**Comment by segator** [comment]
in channels: in your application.yml you are missing the type: parameter as described in the readme.

type: tvheadend or json and the respective parameters.

**Comment by segator** [comment]
closing as no answer
