### ISSUE TITLE
will not start

### ISSUE THREAD

**Issue by olili** [segator/proxylive#33]
Dear all,

I'm a little bit lost.
I spend inbetween almost one day to put this promising application into operation. But still wihout any success. 
I tried it with docker as well with bare metal debian10/11 setups. It is always throwing expceptions in startup and restarting. 
Reading the issues I conclude that application.yaml is a cruical topic. 
So, could some body provide me a simple expample file that is definitly working? 

Many thanks in advance, O.

**Comment by segator** [comment]
Hi, first of all I not maitaining any more this application as I not using it :(

but happy you want to have a look on it.
I suggest you go through the readme where I explain how to configure the application.yaml, without it the application won't start.

If you still have issues feel free to send me  the file and I will have a look.

**Comment by olili** [comment]
Hi,
I used attached appliction.yaml, derrived from the readme.
[application.zip](https://github.com/user-attachments/files/15875807/application.zip)
Any hint?
Which application do you use now to manage the iptv proxy ts/hls conversion?
Thx. O.

**Comment by segator** [comment]
can you please provide me the boot log? the application.yml seems OK to me, probably the issue is at runtime. do you have tvh authentication? remember to pass credentials. maybe with the log I can figure out what is wrong.

I actually not running any iptv personal server. but proxylive worked for my and my friend for 4y without issues :)

**Comment by olili** [comment]
thx. 
Here is my startup log: 
`

root@debian:~# docker container run --name=proxylive -p 8080:8080 -it -v /root/application.yml:/app/application.yml:ro --rm segator/proxylive:sha-650c4fe bash
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
               (      (         )       )       )   (      (
               )\ )   )\ )   ( /(    ( /(    ( /(   )\ )   )\ )
              (()/(  (()/(   )\())   )\())   )\()) (()/(  (()/(   (   (    (
 ___   ___     /(_))  /(_)) ((_)\   ((_)\   ((_)\   /(_))  /(_))  )\  )\   )\      ___   ___
|___| |___|   (_))   (_))     ((_)  __((_) __ ((_) (_))   (_))   ((_)((_) ((_)    |___| |___|
              | _ \  | _ \   / _ \  \ \/ / \ \ / / | |    |_ _|  \ \ / /  | __|
              |  _/  |   /  | (_) |  >  <   \ V /  | |__   | |    \ V /   | _|
              |_|    |_|_\   \___/  /_/\_\   |_|   |____| |___|    \_/    |___|

            (         )              (                         (                     (
       (    )\ )   ( /(      (       )\ )      (       (       )\ )    *   )         )\ )
     ( )\  (()/(   )\())     )\     (()/(      )\      )\     (()/(  ` )  /(   (    (()/(
     )((_)  /(_)) ((_)\   ((((_)(    /(_))   (((_)  ((((_)(    /(_))  ( )(_))  )\    /(_))
    ((_)_  (_))     ((_)   )\ _ )\  (_))_    )\___   )\ _ )\  (_))   (_(_())  ((_)  (_))
     | _ ) | _ \   / _ \   (_)_\(_)  |   \  ((/ __|  (_)_\(_) / __|  |_   _|  | __| | _ \
     | _ \ |   /  | (_) |   / _ \    | |) |  | (__    / _ \   \__ \    | |    | _|  |   /
     |___/ |_|_\   \___/   /_/ \_\   |___/    \___|  /_/ \_\  |___/    |_|    |___| |_|_\


2024-06-18T17:53:10,115 INFO  [main] o.s.b.StartupInfoLogger: Starting Application v1.0-SNAPSHOT using Java 14.0.2 on 884861c24801 with PID 7 (/app/proxyLive.jar started by root in /app)
2024-06-18T17:53:10,123 DEBUG [main] o.s.b.StartupInfoLogger: Running with Spring Boot v2.6.1, Spring v5.3.13
2024-06-18T17:53:10,124 INFO  [main] o.s.b.SpringApplication: The following profiles are active: =
2024-06-18T17:53:18,326 INFO  [main] o.s.b.w.e.t.TomcatWebServer: Tomcat initialized with port(s): 8080 (http)
2024-06-18T17:53:18,355 INFO  [main] o.a.j.l.DirectJDKLog: Initializing ProtocolHandler ["http-nio-8080"]
2024-06-18T17:53:18,357 INFO  [main] o.a.j.l.DirectJDKLog: Starting service [Tomcat]
2024-06-18T17:53:18,411 INFO  [main] o.a.j.l.DirectJDKLog: Starting Servlet engine: [Apache Tomcat/9.0.55]
2024-06-18T17:53:18,740 INFO  [main] o.a.j.l.DirectJDKLog: Initializing Spring embedded WebApplicationContext
2024-06-18T17:53:18,741 INFO  [main] o.s.b.w.s.c.ServletWebServerApplicationContext: Root WebApplicationContext: initialization completed in 8197 ms
2024-06-18T17:53:20,936 DEBUG [main] o.s.w.f.GenericFilterBean: Filter 'JWTBasicFilter' configured for use
2024-06-18T17:53:21,022 INFO  [main] c.g.s.p.s.EPGService: Refreshing EPG
2024-06-18T17:53:21,621 WARN  [main] o.s.c.s.AbstractApplicationContext: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'frontendController' defined in URL [jar:file:/app/proxyLive.jar!/BOOT-INF/classes!/com/github/segator/proxylive/controller/FrontendController.class]: Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'createChannelService' defined in class path resource [com/github/segator/proxylive/service/ChannelServiceFactory.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.segator.proxylive.service.ChannelService]: Factory method 'createChannelService' threw exception; nested exception is java.lang.NullPointerException
2024-06-18T17:53:21,626 INFO  [main] o.a.j.l.DirectJDKLog: Stopping service [Tomcat]
2024-06-18T17:53:21,815 INFO  [main] o.s.b.a.l.ConditionEvaluationReportLoggingListener:

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-06-18T17:53:21,918 ERROR [main] o.s.b.SpringApplication: Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'frontendController' defined in URL [jar:file:/app/proxyLive.jar!/BOOT-INF/classes!/com/github/segator/proxylive/controller/FrontendController.class]: Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'createChannelService' defined in class path resource [com/github/segator/proxylive/service/ChannelServiceFactory.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.segator.proxylive.service.ChannelService]: Factory method 'createChannelService' threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290)
        at com.github.segator.proxylive.Application.main(Application.java:38)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'createChannelService' defined in class path resource [com/github/segator/proxylive/service/ChannelServiceFactory.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.segator.proxylive.service.ChannelService]: Factory method 'createChannelService' threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:486)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
        ... 27 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.segator.proxylive.service.ChannelService]: Factory method 'createChannelService' threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
        ... 41 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.github.segator.proxylive.service.ChannelServiceFactory.createChannelService(ChannelServiceFactory.java:18)
        at com.github.segator.proxylive.service.ChannelServiceFactory$$EnhancerBySpringCGLIB$$64898954.CGLIB$createChannelService$0(<generated>)
        at com.github.segator.proxylive.service.ChannelServiceFactory$$EnhancerBySpringCGLIB$$64898954$$FastClassBySpringCGLIB$$133530e.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
        at com.github.segator.proxylive.service.ChannelServiceFactory$$EnhancerBySpringCGLIB$$64898954.createChannelService(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 42 common frames omitted

`

**Comment by segator** [comment]
you missed `type: tvheadend`in `channels:`
